#!/usr/bin/env bash
set -eo pipefail

{
  date
  bash -lc "
    exec alerterr \
      --name=qbtprune --on_err='/\\S/' -- \
      flock /tmp/qbtprune_cronjob.lock \
        bundle exec ruby main.rb prune \
          'http://admin:adminqbit@winpc:8080' \
          --radarr='http://localhost:7878/api?apikey=2abbfecdc4264d0988fe7f47c86e9102' \
          --sonarr='http://localhost:8989/api?apikey=9b1c724fb16f423185546fb168522ab5'
  "
} 2>&1 | tee /tmp/qbtprune_cronjob.log
